/**
 * POST /api/ads/adset-strategy
 *
 * Returns recommended Facebook Ads Manager ad set settings (targeting, budget,
 * placements, etc.) generated by OpenAI from brand + product context.
 */

import { NextResponse } from "next/server";
import { generateAdsetStrategy } from "@/lib/ads/adsetStrategy";

type Body = {
  brand?: {
    name?: string;
    tagline?: string;
    mission?: string;
    sellingType?: "products" | "saas" | "services";
    websiteUrl?: string;
    domain?: string;
  };
  product?: { title?: string; description?: string; price?: string };
};

export async function POST(request: Request) {
  try {
    let body: Body;
    try {
      body = await request.json();
    } catch {
      return NextResponse.json({ error: "Invalid JSON" }, { status: 400 });
    }

    const brand = body.brand;
    const brandName = brand?.name?.trim();
    if (!brandName) return NextResponse.json({ error: "Missing brand.name" }, { status: 400 });

    const strategy = await generateAdsetStrategy({
      brandName,
      tagline: brand?.tagline ?? null,
      mission: brand?.mission ?? null,
      sellingType: brand?.sellingType ?? null,
      websiteUrl: brand?.websiteUrl,
      domain: brand?.domain,
      productTitle: body.product?.title ?? undefined,
      productDescription: body.product?.description ?? null,
      productPrice: body.product?.price ?? null,
    });

    return NextResponse.json({ strategy });
  } catch (err) {
    console.error("[adset-strategy] Error:", err);
    const message = err instanceof Error ? err.message : "Ad set strategy generation failed";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
